### ISSUE TITLE
Add a cluster discovery mechanism

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStoreDB-Client-Java#10]
We need to be able to connect to an Event Store cluster. In the Event Store Dotnet Client we currently use the gossip endpoint which is http based. We are working on a gRPC based implementation.

**Comment by YoEight** [comment]
Done https://github.com/EventStore/EventStoreDB-Client-Java/commit/d375fdf8075f8baa854d7dcc78132a138982f27b
