### ISSUE TITLE
Java RFC - 021 Projections API Control Operations Implementation

### ISSUE THREAD

**Issue by tambeau** [EventStore/EventStoreDB-Client-Java#112]
@tambeau commented on [Fri Nov 05 2021](https://github.com/EventStore/home/issues/657)

Implementation of Control Operations for Java gRPC Projections API

Control
- [x] Restart Projections Subsystem
- [x] Abort (Name) - WriteCheckpoint set to false
- [x] Disable (Name) - WriteCheckpoint set to true
- [x] Enable (Name)
- [x] Reset (Name) - Remove WriteCheckpoint
- [x] Delete (Name, DeleteStateStream, DeleteCheckpointStream, DeleteEmittedStream)

---

@tambeau commented on [Mon Nov 08 2021](https://github.com/EventStore/home/issues/657#issuecomment-963281906)

Issue moved to [EventStore/EventStore-Client-NodeJS #235](https://github.com/EventStore/EventStore-Client-NodeJS/issues/235) via [**ZenHub**](https://www.zenhub.com/)

**Comment by linde9821** [comment]
Hi :) Any updates regarding the progress of projection management with the java client?

**Comment by pvanbuijtene** [comment]
@linde9821 I'm currently looking into it, so should be implemented not too long from now.
