### ISSUE TITLE
Java RFC - 021 Projections API Create Operation Implementation

### ISSUE THREAD

**Issue by tambeau** [EventStore/EventStoreDB-Client-Java#113]
@tambeau commented on [Fri Nov 05 2021](https://github.com/EventStore/home/issues/656)

Implementation of Create Operation for Java gRPC Projections API

Create
- [x] Create Projection (Name, Query, EmitEnabled, TrackEmittedStreams) - Enabled parameter remove always set to false

**Comment by pvanbuijtene** [comment]
Already implemented, will keep as-is for now to prevent breaking changes.

- [x] Remove creation of `Transient` and `OneTime` projections
- [x] Set the defaults for `EmitEnabled` and `TrackEmittedStreams` to false
- [x] Rename `createContinuous` to `createProjection`
- [ ] Add `EmitEnabled` to create, currently not in proto yet

**Comment by sagoez** [comment]
Sorry to re-open with a silly question, why were OneTime projection removed if the [page](https://developers.eventstore.com/clients/dotnet/5.0/projections.html#create-a-one-time-projection) still advertises it or maybe I'm missing something and it was renamed.

**Comment by ylorph** [comment]
@samgj18  : that's the TCP protocol , so in the legacy .net tcp library  it's still there.
We didn' add One Time projection  to the gRPC protocol because we do not think it makes sense to do that from an application perspective .
Most users are using that specific type through the UI .

**Comment by sagoez** [comment]
Ah that makes sense, thank you @ylorph
