### ISSUE TITLE
Java RFC - 021 Projections API State Operations Implementation

### ISSUE THREAD

**Issue by tambeau** [EventStore/EventStoreDB-Client-Java#114]
@tambeau commented on [Fri Nov 05 2021](https://github.com/EventStore/home/issues/655)

Implementation of State Operations for Java gRPC Projections API

State
- [ ] Get Query (Name, Config?)
- [ ] Get Config (Name)
- [x] Get Status (Name)
- [x] Get State (Name, Partition)
- [x] Get Result (Name)

**Comment by pvanbuijtene** [comment]
Still to do:
- [x] Get Result (Name, Partition)
