### ISSUE TITLE
Java RFC - 021 Projections API Statistics Operations Implementation

### ISSUE THREAD

**Issue by tambeau** [EventStore/EventStoreDB-Client-Java#115]
@tambeau commented on [Fri Nov 05 2021](https://github.com/EventStore/home/issues/654)

Implementation of Statistics Operations for Java gRPC Projections API

Statistics
- [x] Get Statistics (name)
- [x] List All
- [ ] List

**Comment by pvanbuijtene** [comment]
Not sure why there are to `List`s mentioned, there's only 1 in the RFC.
