### ISSUE TITLE
Java RFC - 021 Projections API Update Operations Implementation

### ISSUE THREAD

**Issue by tambeau** [EventStore/EventStoreDB-Client-Java#116]
@tambeau commented on [Fri Nov 05 2021](https://github.com/EventStore/home/issues/653)

Implementation of Update Operations for Java gRPC Projections API

Update
- [x] Projection (Name, Query, EmitEnabled)
- [ ] Config (Name, Config)

**Comment by pvanbuijtene** [comment]
Update config is not available yet.
