### ISSUE TITLE
Add and publish JavaDoc for all public facing types

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStoreDB-Client-Java#12]
We should add JavaDoc comments to all public facing types, and add a build lint that produces errors going forward. The JavaDoc should be published in native format as part of the documentation website.

cc @mat-mcloughlin

**Comment by michael-schnell** [comment]
This is really a severe issue for everyone who wants to use the Java client API. Any idea when this will be solved?

**Comment by YoEight** [comment]
@michael-schnell Here's what the javadoc looks like:

https://eventstore.github.io/EventStoreDB-Client-Java

 Mind you it's based on the `docs` branch. When the PR merged, the javadoc will update itself on every release.

**Comment by michael-schnell** [comment]
Looks great!
