### ISSUE TITLE
Log4Shell vulnerability checks

### ISSUE THREAD

**Issue by YoEight** [EventStore/EventStoreDB-Client-Java#121]

**Comment by YoEight** [comment]
We run [Grype] on both the source code and the latest Jar and the result is the Java gPRC client is not exposed to Log4Shell. We also doubled-checked that we don't even have a dependency to `log4j`, even transitively.

[Grype]: https://github.com/anchore/grype

**Comment by jageall** [comment]
thanks @YoEight , closing this but it should answer any questions people have about it
