### ISSUE TITLE
Implementation of State Operations for Java gRPC Projections API

### ISSUE THREAD

**Issue by tambeau** [EventStore/EventStoreDB-Client-Java#124]
Implementation of State Operations for Java gRPC Projections API

State
- [ ] Get Query (Name, Config?) **blocked - Server Update Required**
- [ ] Get Config (Name) **blocked - Server Update Required**
- [ ] Get Status (Name) **blocked - Server Update Required**
- [ ] Get State (Name, Partition)  **missing partition option**
- [ ] Get Result (Name, Partition) **blocked**

**Comment by YoEight** [comment]
That feature is no longer supported.
