### ISSUE TITLE
Getting NullPointerException while setting stream metadata from the Java Client latest version

### ISSUE THREAD

**Issue by lakshdeepsingheventstore** [EventStore/EventStoreDB-Client-Java#137]
The client code crashes when using EventStoreDB Java Client latest version (v2..2.0) to set stream metadata. The same code works perfectly fine when using EventStoreDB Java Client v2.0.0.

**Comment by dhirajkumar94** [comment]
@lakshdeepsingheventstore Don't you mean it crashes using version 1.1.1-SNAPSHOT?

**Comment by YoEight** [comment]
I need more information on this. What version are they specifically using? If the code is working on version 2.0.0, considering it's the current release version, where is the problem?

**Comment by dhirajkumar94** [comment]
@YoEight As per my test results, the code throws NullPointerException while using Java client version 1.1.1-SNAPSHOT, and it's working when I upgraded it to 2.0.0.
