### ISSUE TITLE
Reading a deleted stream should throw a StreamDeletedException with boolean flag soft/hard

### ISSUE THREAD

**Issue by michael-schnell** [EventStore/EventStoreDB-Client-Java#149]
Currently hard deleting a stream and reading/writing/deleting from it afterwards results in a "FAILED_PRECONDITION":
`io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Event stream 'accounts' is deleted.`

It would be nice to have a dedicated exception for that condition: 
`com.eventstore.dbclient.StreamDeletedException`

The FAILED_PRECONDITION is very generic and requires parsing the error message to react programmatically on that situtation, which is not really nice. Having a dedicated exception would solve this issue.

Actually we have three different situations when reading a stream that was either soft/hard deleted or does not exists:

1. Never existed => StreamNotFoundException
2. Was soft deleted =>  StreamDeletedException(type = soft)   // Currently it has StreamNotFoundException"
3. Was hard deleted => StreamDeletedException(type = hard)

It would even better to use "StreamDeletedException" for both deleted situations and add a boolean flag to the exception that signals wether it was soft or hard deleted.

**Comment by YoEight** [comment]
Good idea! However, deleting a stream will never throw a `StreamNotFoundException`. Delete operations accept an `ExpectedRevision`. It's `StreamDeletedException` or `WrongExpectedVersionException`. We can't know if it was a soft (delete) or hard (tombstome) operation though.
