### ISSUE TITLE
Several classes miss a "toString()" method

### ISSUE THREAD

**Issue by michael-schnell** [EventStore/EventStoreDB-Client-Java#150]
While debugging or logging it's helpful to have a visual representation of the instance.

A class like "DeleteResult" for example currently has no "toString()" method.

It could look like this:

```
@Override
public String toString() {
    return "DeleteResult [logPosition=" + logPosition + "]";
}
```

**Comment by YoEight** [comment]
Some work done here: https://github.com/EventStore/EventStoreDB-Client-Java/pull/204

**Comment by michael-schnell** [comment]
Cool. Many tnx.
