### ISSUE TITLE
Improve Kotlin support

### ISSUE THREAD

**Issue by nhajratw** [EventStore/EventStoreDB-Client-Java#159]
Usage of Kotlin data classes for domain objects is very desirable as it provides immutability, etc.

Currently data classes cannot be used because the jackson deserialization process requires an empty default constructor.

The [jackson-module-kotlin](https://github.com/FasterXML/jackson-module-kotlin) library provides just the hooks needed in order to get this working. It should just be a matter of adding the kotlin module if this library is detected on the classpath.

[This is an example](https://github.com/spring-projects/spring-framework/blob/3dc84c2d92c0fb64e23780f840c563cf4a1e483f/spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java#L837-L848) of how Spring Framework does it.

**Comment by matthewadams** [comment]
Given that this issue's title is "Improve Kotlin support", I might also request that you provide a Kotlin client that presents pure Kotlin idioms, delegating to the Java client.  In particular, I'd be looking for support for Kotlin coroutines.  If that merits its own issue, I'll happily create it.
