### ISSUE TITLE
eventType: "$>" when subscribing to projections

### ISSUE THREAD

**Issue by guiwoda-inviu** [EventStore/EventStoreDB-Client-Java#166]
Using `EventStoreDBPersistentSubscriptionsClient#subscribe` or `EventStoreDBClient#subscribeToStream` pointing to an event type projection (`$et-com.example.SomeEvent`) is rendering the following result.

```
streamId = "$et-com.example.SomeEvent"
streamRevision = {StreamRevision@9919} "0"
eventId = {UUID@9920} "0336fb99-09fa-4c06-89ec-1e39f78b4bb8"
eventType = "$>"
eventData = {byte[23]@9922} [...]
created = {Instant@9924} "2022-07-26T21:49:37.141969800Z"
position = {Position@9925} "18446744073709551615/18446744073709551615"
contentType = "application/octet-stream"
```

Any ideas?

**Comment by YoEight** [comment]
You need to enable link resolution when reading events emitted by projections: https://developers.eventstore.com/clients/grpc/reading-events.html#resolvelinktos

May I advise you to reach out on [Discuss] first? We prefer to restrict Github for confirmed issues.

[Discuss]: https://discuss.eventstore.com/
