### ISSUE TITLE
Make fetching server info an async operation

### ISSUE THREAD

**Issue by tambeau** [EventStore/EventStoreDB-Client-Java#169]
I would suggest doing as we do with other clients (Go or the Rust clients for example). Meaning getting the server version should be an async operation. I truly believed that was the case since the beginning, but maybe I overlooked some changes made in recent PRs.

If it takes too much time for you to fix it, keep the implementation you did, and I'll change it in another PR. Please create an issue, so I remember.

_Originally posted by @YoEight in https://github.com/EventStore/EventStoreDB-Client-Java/pull/165#discussion_r934051760_

**Comment by YoEight** [comment]
Done here: https://github.com/EventStore/EventStoreDB-Client-Java/pull/177
