### ISSUE TITLE
Incorrect regex in documentation

### ISSUE THREAD

**Issue by causton81** [EventStore/EventStoreDB-Client-Java#200]
This Java example has the line `String excludeSystemEventsRegex = "/^[^\\$].*/";` NOTE surrounding `/` 
https://developers.eventstore.com/clients/grpc/subscriptions.html#filtering-out-system-events

I have to remove the outer `/` and use just `final String excludeSystemEventsRegex = "^[^\\$].*";`

Java client: 4.0.0
ESDB docker container: tags/oss-v21.10.8

**Comment by YoEight** [comment]
Thanks @causton81 for reporting that issue.
