### ISSUE TITLE
Inconsistent behaviour of EventSToreDBClient.tombstoneStream() depending on which variant is called (4.0.0 client)

### ISSUE THREAD

**Issue by thomdreilly** [EventStore/EventStoreDB-Client-Java#201]
The single-argument variant of tombstoneStream and the multiple-argument variant behave differently, as the softDelete flag is set to true in the former case, and false in the latter.

https://github.com/EventStore/EventStoreDB-Client-Java/blob/2189f6bd17289b40fad8784ece2b2e75512750f2/db-client-java/src/main/java/com/eventstore/dbclient/EventStoreDBClient.java#L340

I believe this line has a typo and should actually be:
`        return this.tombstoneStream(streamName, DeleteStreamOptions.get());`

**Comment by YoEight** [comment]
@thomdreilly Thanks for opening the issue and nice catch!
