### ISSUE TITLE
Make EventData constructor public

### ISSUE THREAD

**Issue by roegerle** [EventStore/EventStoreDB-Client-Java#252]
Can we get the package private constructor of EventData public instead? Maybe I'm missing something but I don't see a way to set the mime type to anything of than application/json and application/octet-stream.

**Comment by cdevarenne** [comment]
Thank you for asking @roegerle, custom mime types are not supported at this time.

**Comment by roegerle** [comment]
I'm evaluating EventStore so bear with me.

The end goal was to use something other than jackson for Java serialization. 

Not using any of the json methods on the client and just using byte arrays obviously works just fine but the dash board doesnt format the json very well with a mime type of ther than json.

Any suggestions?

**Comment by cdevarenne** [comment]
Hey Robert,

Thanks for providing some context. By dashboard do you mean the web UI? I
understand what you are saying now. Let me get back to you on this ASAP.
Thanks

**Comment by roegerle** [comment]
Yes.  I removed that comment though after looking at the api and the commit history of the project.  I missed this method...

EventDataBuilder | json​(java.lang.String eventType, byte[] eventData)

Which I haven't tried but I suspect would suit my needs just fine.  My problem is I have tons of custom serialization code in Gson and don't want to mess around with Jackson.

**Comment by YoEight** [comment]
@roegerle That is expected. The UI will only display payload in a json format. Same with user defined projections, those will only work if the events they are dealing with have json payload. You can use any other format, the database doesn't care but all the built-ins visualization tools and the projections I talked about won't be able to process the payload.

**Comment by YoEight** [comment]
> Which I haven't tried but I suspect would suit my needs just fine. My problem is I have tons of custom serialization code in Gson and don't want to mess around with Jackson.

Rest assured you won't have to. Use the `binary` smart constructor/method and store your gson-format events stress-free. it's for usecases like that the binary format or `application/octet-stream` is meant for :)
