### ISSUE TITLE
Support "CaughtUp" gRPC control message for subscriptions when a subscription becomes live

### ISSUE THREAD

**Issue by Grisu118** [EventStore/EventStoreDB-Client-Java#253]
We tried to update to eventstore 23.10.0 and encountered an issue.

With the introduction of the new CaughtUp control message, there is no longer a checkpoint emitted at this point. Which breaks our usecase as we used this to emulate the CaughtUp. 
Instead of this a warning is logged
`2023-11-09T12:19:03.418576641Z [WARN] .d.AbstractRegularSubscription: Confirmed subscription a16d6684-1ddb-4bf7-8dac-5acec7af9146 received non-{event,checkpoint} variant`

So support for the new messages would be nice and would allow updating to the new lts eventstore

Related: https://github.com/EventStore/EventStore/pull/3899

**Comment by YoEight** [comment]
Got the PR ready. When merged, I'll release a new version as soon as possible.

**Comment by YoEight** [comment]
@Grisu118 the feature is available on 5.2.0 version which is in Maven Central already
