### ISSUE TITLE
Question: throwOnAppendFailure removed, was it unused?

### ISSUE THREAD

**Issue by TomMante** [EventStore/EventStoreDB-Client-Java#255]
Hello,

I am currently looking to upgrade from 4.3.0 to 5.2.0 and looking at the changes, i saw that `throwOnAppendFailure` was removed from the connection settings in this pr:
https://github.com/EventStore/EventStoreDB-Client-Java/pull/243

I was trying to see if it was used before or not, it seems not, could you confirm that this is an unused parameter? Can I just ignore it?

Thank you!

**Comment by YoEight** [comment]
Hey @TomMante,

Rest assured, `throwOnAppendFailure` was never implemented in the first place in the Java client. The Java client always throws on append failure.
