### ISSUE TITLE
Adding Custom Headers

### ISSUE THREAD

**Issue by tskinner-oppfi** [EventStore/EventStoreDB-Client-Java#286]
I'm building an eventstore cluster that utilizes the [trusted intermediary](https://developers.eventstore.com/server/v24.6/security.html#trusted-intermediary) strategy for authentication. This will require that our clients send a Authorization bearer header with a token. Is there a simple way to do this with the java client? If not can it be added?

**Comment by YoEight** [comment]
Hey @tskinner-oppfi.

We could definitely expose an API for you to add custom headers

**Comment by tskinner-oppfi** [comment]
Awesome that would be fantastic. Is there a rough timeline in which that could be accomplished?

**Comment by tskinner-oppfi** [comment]
Can I make a PR? Are you are open to contributions?

**Comment by YoEight** [comment]
Hey @tskinner-oppfi,

We don't have much bandwidth right now for non urgent features, so unless you can wait 1 week or 2, I suggest you to push your own PR. I'll make sure to review it as promptly as possible.

**Comment by tskinner-oppfi** [comment]
No worries. As I was looking through the code I found that you actually expose the ability to add grpc ClientInterceptors via the esdb client builder. If I'm not mistaken I can add an interceptor to add a header. If that is true we can close this issue.

**Comment by YoEight** [comment]
@tskinner-oppfi I added a more direct approach with this PR

**Comment by tskinner-oppfi** [comment]
awesome thank you!

**Comment by YoEight** [comment]
@tskinner-oppfi The feature is available in the 5.4.2 release.
