### ISSUE TITLE
NPE if event has been deleted

### ISSUE THREAD

**Issue by rickardoberg** [EventStore/EventStoreDB-Client-Java#291]
https://github.com/EventStore/EventStoreDB-Client-Java/blame/94ee76accdd7fde76cd95a8dceb18df2df2ababe/db-client-java/src/main/java/com/eventstore/dbclient/ClientTelemetry.java#L125

The above line can cause NullPointerException if the event has been deleted. Add null check please.

**Comment by w1am** [comment]
Hi @rickardoberg 

Thanks for letting us know about this issue.

The patch is available on `v5.4.3` and feel free to reach out if any other issues come up! 👍
