### ISSUE TITLE
Incompatible with dynamic JVM languages

### ISSUE THREAD

**Issue by AdamClements** [EventStore/EventStoreDB-Client-Java#66]
Due to a [bug in the JVM](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4283544) (still open since 1999) Reflection vs Compiler gives different access levels to package-private classes, i.e. inheriting a public method from a protected class works fine for javac but doesn't work when using the reflection API as various dynamic JVM languages, (and maybe spring etc?) do.

I hit this when trying to use the new 1.0 EventStore from Clojure, it's currently impossible to call SubscribeToAllOptions.fromPosition because its method definition is in a package protected class.

As it stands I'm either stuck on 0.5 or need to write a pure java wrapper around various chunks of the API

**Comment by AdamClements** [comment]
Note, I'm happy to submit patches for this if we can agree an approach you'd be willing to accept for this, I can see why it's been made non public, presumably to keep the api clean while still reusing components.

**Comment by YoEight** [comment]
Hi @AdamClements

Thanks for submitting that issue. We'll be happy to discuss your approach in a PR!

**Comment by AdamClements** [comment]
We've decided to swap out eventstore due other deployment-at-scale issues, so I'm probably not going to be following this up with a PR, sorry
