### ISSUE TITLE
Events are inserted twice even though they have the same id

### ISSUE THREAD

**Issue by johanhaleby** [EventStore/EventStoreDB-Client-Java#69]
I'm finding some surprising behavior that I suspect is a bug. In the [documentation](https://developers.eventstore.com/clients/grpc/appending-events/#eventid) of eventId it says:

> If two events with the same Uuid are appended to the same stream in quick succession EventStoreDB will only append one copy of the event to the stream.

But if I just write a simple snippet like this:

```java
UUID id = UUID.randomUUID();
eventStoreDBClient.appendToStream("name", EventData.builderAsBinary(id, "type1", "data".getBytes(UTF_8)).build()).join();
eventStoreDBClient.appendToStream("name", EventData.builderAsBinary(id, "type1", "data".getBytes(UTF_8)).build()).join();

System.out.println("### " + eventStoreDBClient.readStream("name").join().getEvents().size());
```

Then it'll print `### 2` (i.e. two events were appended)

If I change it to:

```
EventData eventData = EventData.builderAsBinary(UUID.randomUUID(), "type1", "data".getBytes(UTF_8)).build();
eventStoreDBClient.appendToStream("name", eventData).join();
eventStoreDBClient.appendToStream("name", eventData).join();

System.out.println("### " + eventStoreDBClient.readStream("name").join().getEvents().size());
```

Then it'll print `### 1` (i.e. one event was appended).

In my world, these two code snippets ought to yield the same result (i.e. printing `### 1`). Since I'm new to ESDB I'm not sure if it's a bug or not, but it seems like very strange behavior to me.

I'm using version 1.0.0 and ESDB running in Docker (image is `eventstore/eventstore:21.2.0-buster-slim`).

**Comment by YoEight** [comment]
The patch is available on the latest snapshot version of the client if you are interested: https://github.com/EventStore/EventStoreDB-Client-Java/issues/68#issuecomment-827502978
