### ISSUE TITLE
Stream Metadata

### ISSUE THREAD

**Issue by jselamy** [EventStore/EventStoreDB-Client-Java#74]
Is there a way in this java client to have Operations on the Metadata of a stream ? 

- ACL's
- etc

**Comment by YoEight** [comment]
There is no dedicated operation for reading/writing stream's metadata. Under the hood, it's a regular `readStream`/`appendStream`. The main difference is about reading a stream metadata's stream `$$your_stream_name`. The Java client doesn't have a first class support for reading/writing metadata yet but you can do it on your application codebase to unblock you if it's urgent: https://developers.eventstore.com/server/v21.2/docs/streams/metadata-and-reserved-names.html

**Comment by jselamy** [comment]
can you show me a simple example on how to proceed ? 

Or i would have to use the HTTP Api to perform such action for now ?

**Comment by YoEight** [comment]
No need to use HTTP, use the Java gRPC client `readStream`/`appendStream` functions. The stream name would be `$$your_stream_name` and the event's type when appending metadata in the stream metadata's stream is `$metadata`. I might have some time to implement the feature properly within the next 2 weeks.

**Comment by YoEight** [comment]
@jselamy It you want to try it out, our latest snapshot version is available on Sonatype. See: https://github.com/EventStore/EventStoreDB-Client-Java#snapshot-versions
