### ISSUE TITLE
nodePreference seems to always connect to the same node

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStoreDB-Client-Java#83]
I've noticed the following behaviour with nodePreference:

`nodePreference=follower` - seems to always connect to the same follower node instead of randomly choosing one among them (stopping and starting the client makes it connect to the same node every time)
`nodePreference=random` - seems to always connect to the same node (among all nodes that are currently alive)
`nodePreference=leader` - works fine since there's a single leader

connection string:
```
esdb://admin:changeit@127.0.0.1:2113,127.0.0.2:2113,127.0.0.3:2113?tls=true&tlsVerifyCert=false&nodePreference=NODEPREFERENCE
```

I've tested with version 1.0.0 and `trunk`

**Comment by dpasek-senacor** [comment]
@shaan1337 Yes, this is a problem in the node selection algorithm. I have prepared an PR for this.
