### ISSUE TITLE
Java gRPC Client Streams API Compliance - Minimum Viable Tier

### ISSUE THREAD

**Issue by tambeau** [EventStore/EventStoreDB-Client-Java#90]
Streams API:
This should eventually be defined in RFC [Home#551](https://github.com/EventStore/home/issues/551):

- [x] AppendToStream
  - [x] Append
- [ ] **Delete** - `Delete` should not take an option for `isSoftDelete`
- [ ] **Tombstone** - A `Tombstone` operation should be added, and the ability to tombstone a stream in `Delete` should be removed
- [x] ReadAll
- [x] ReadStream
- [x] SubscribeToAll
  - [x] With Filter
- [x] SubscribeToStream
- [x] GetStreamMetadata
- [x] SetStreamMetadata

**Comment by YoEight** [comment]
Done
