### ISSUE TITLE
No support for readStreamAsync ??

### ISSUE THREAD

**Issue by chrispoulsen** [EventStore/EventStoreDB-Client-Java#95]
For some reason it seems like the Java client always wants to realize all events in a List before returning. 

The [docs](https://developers.eventstore.com/clients/grpc/reading-events/reading-from-a-stream.html#checking-for-stream-presence) are also way off, as they talk about some `ReadStreamResult` which obviously makes no sense if the method returns a List

**Comment by YoEight** [comment]
There is a PR on this subject #79 

The reason the PR hasn't been merged yet is we want to be sure it is the right approach. There's a discussion in this PR thread. Would mind sharing what you would like to have there?

Thanks for your time!

**Comment by dpasek-senacor** [comment]
@chrispoulsen See new PR on streaming of large event sets. Feedback/thoughts welcome.

#106
